In [3]:
%run -i 02_array.ipynb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

Podemos conocer el tipo de datos del array consultando la propiedad .dtype

In [12]:
arr=np.array([1,2,3,4])
arr.dtype # to check the data type of the array

dtype('int64')

Si queremos usar otro tipo de dato, lo podemos definir en la declaración del array.

In [14]:
arr=np.array([1,2,3,4],dtype="float64") # to define the data type of the array, using dtype, it has many options like int, float, bool, etc
arr.dtype 
arr

array([1., 2., 3., 4.])

Ahora vemos que los valores están con punto decimal.



In [6]:
arr

array([1., 2., 3., 4.])

Si ya se tiene el array definido, se utiliza el método .astype() para convertir el tipo de dato.

In [7]:
arr=np.array([1,2,3,4])
arr=arr.astype(np.float64) # we can also use astype to change the data type of the array in case we want to change a defined array.
arr

array([1., 2., 3., 4.])

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.



In [15]:
arr=np.array([0,1,2,3,4])
arr=arr.astype(np.bool_) # we can also change the data type to boolean using astype
arr

array([False,  True,  True,  True,  True])

También podemos convertir los datos en tipo string.



In [16]:
arr=np.array([0,1,2,3,4])
arr=arr.astype(np.string_) # we can also change the data type to string using astype
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

De igual manera, se puede pasar de string a número.



In [17]:
arr=np.array(["0","1","2","3","4"])
arr=arr.astype(np.int8) # we can also change the data type to int using astype
arr



array([0, 1, 2, 3, 4], dtype=int8)

Si un elemento no es de tipo número, el método falla.



In [18]:
# arr=np.array(["hola","0","1","2","3","4"])
# arr=arr.astype(np.int8)
# arr

El array de Numpy únicamente puede tener un único tipo de datos en el cual va a trabajar. No puedo tener la mitad del array en int y la otra mitad en bool.