In [1]:
%run -i 07_main_function.ipynb

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[[[[[[[[[1 2 3]]]]]]]]]]
[[1 2 3]]
[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
[12 13 16 16  0 13  2 13 13 16]
[16 16]
[13 13 16 16 16]
[[12 13 16 16  0]
 [13  2 13 13 16]]
[12 13 16 16  0 13  2 13 13 16]
0
4
[4 1]
[ 0  2 12 13 13 13 13 16 16 16]
[[ 0  2 12 13 13]
 [13 13 16 16 16]]


.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

In [4]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tomamos un trozo del array original



In [7]:
arr[0:6]

trozo_de_arr=arr[0:6]

Queremos pasar todas nuestras variables a 0



In [11]:
trozo_de_arr[:]=0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.



In [12]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Con .copy() creamos una copia para no dañar nuestro array original

In [17]:
arr_copy=arr.copy()
arr_copy[:]=100
print(arr_copy)
arr

[100 100 100 100 100 100 100 100 100 100 100]


array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Esta función te ayudará a prevenir muchos errores y tener más confianza a la hora de manipular los datos