In [2]:
%run -i 08_copy.ipynb

[100 100 100 100 100 100 100 100 100 100 100]


Las condiciones nos permiten hacer consultas más específicas.



In [12]:
arr=np.linspace(1,10,10, dtype="int8") # usamos linspace para crear un array de 10 elementos entre 1 y 10 de tipo int8 (entero de 8 bits)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Regresa un array de booleanos dónde la condición se cumple.



In [8]:
indices_cond=arr>5 # creamos un array de booleanos con los elementos que cumplen la condición
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Regresa los valores para dónde la condiciones True.



In [13]:
arr[indices_cond] # seleccionamos los elementos que cumplen la condición

array([ 6,  7,  8,  9, 10], dtype=int8)

**Múltiples condiciones.**

In [14]:
arr[(arr>5)&(arr<9)] # seleccionamos los elementos que cumplen la condición compuesta (AND) entre 5 y 9

array([6, 7, 8], dtype=int8)

Modificar los valores que cumplan la condición.



In [15]:
arr[arr>5]=99 # asignamos 99 a los elementos que cumplen la condición
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)