In [1]:
%run -i 09_condiciones.ipynb

42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[[[[[[[[[1 2 3]]]]]]]]]]
[[1 2 3]]
[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


Existen diferentes operaciones que se pueden usar para los arrays de NumPy.



In [8]:
lista=[1,2]
lista

[1, 2]

Una lista de Python entiende que quieres duplicar los datos. No es lo que buscamos.



In [9]:
lista*2 

[1, 2, 1, 2]

Pero Numpy lo entiende mucho mejor



In [10]:
arr=np.arange(0,10) # arange crea un array de 0 a 9
arr2=arr.copy() # copia el array arr en arr2 buenas practicas

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr*2 # Multiplica cada elemento por 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Operación suma de vectores:



In [12]:
arr+2 # Suma 2 a cada elemento

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

División con un vector


Como en este caso la primera posición del array es 0, muestra un error pero, no detiene el proceso.

In [13]:
1/arr # Divide 1 por cada elemento

/tmp/ipykernel_54473/3752231290.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr # Divide 1 por cada elemento


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Elevar a un vector:



In [14]:
arr**2 # Eleva al cuadrado cada elemento

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Sumar dos arrays de igual dimensiones las hace elemento por elemento:



In [15]:
arr+arr2 # Suma elemento a elemento

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Lo mismo aplica para matrices.



In [16]:
matriz=arr.reshape(2,5) # reshape change the shape of the array, in this case from 1x10 to 2x5
matriz2=matriz.copy()   # we copy the array to another variable
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz-matriz2 # Substract element to element

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Una operación importante es la de punto por punto, aquí dos formas de hacerla:



In [18]:
print(matriz.T) # Transpose the matrix, change the rows to columns and columns to rows

np.matmul(matriz,matriz2.T) # we use matmul to multiply the matrix, in this case we multiply the matrix by its transpose

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


array([[ 30,  80],
       [ 80, 255]])

In [19]:
matriz@matriz2.T # we can also use the @ symbol to multiply the matrix by its transpose


array([[ 30,  80],
       [ 80, 255]])