In [46]:
#Import previos notebook.
%run -i 01_numpy.ipynb

El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

In [47]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9] 
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Volvemos nuestra lista, un array



In [48]:
arr=np.array(lista); # Convert list to numpy array using np.array.
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Una matriz son varios Vectores o listas agrupadas una encima de la otra, es como una tabla de Excel



In [49]:
matriz=[[1,2,3],[4,5,6],[7,8,9]] # Create a list of lists.

matriz = np.array(matriz) # Convert list of lists to numpy array.

matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

In [50]:
arr[0] # Access the first element of the array.

1

| Index | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
|-------|---|---|---|---|---|---|---|---|---|
| 0     | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |

Es posible operar directamente con los elementos. 

In [51]:
arr[0]+arr[5] # Access the first and the figth element of the array and sum them.

7

En el caso de las matrices, al indexar una posición se regresa el array de dicha posición.

In [52]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
matriz[0] # Access the first row of the matrix.


array([1, 2, 3])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

Nota: El primer elemento selecciona las filas, el segundo elemento las columnas

In [54]:

matriz 
#matriz[0,2]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
matriz[0,2] # Access the first row and the third column of the matrix.

3

## Slicing


Nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5.

In [56]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[1:6] # Access the second to the sixth element -1 of the array.

array([2, 3, 4, 5, 6])

Si no se ingresa el valor de inicio, se toma el inicio como la posición 0.

In [58]:
arr[:6] # Access the first to the sixth element -1 of the array.

array([1, 2, 3, 4, 5, 6])

En cambio, si no se le da una posición final, se regresan todos los elementos hasta el final del array

In [59]:
arr[2:] # Access the third to the last element of the array.

array([3, 4, 5, 6, 7, 8, 9])

También se puede trabajar por pasos.

En este ejemplo de 3 en 3.
Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

In [60]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[::3] # Access every third element of the array starting from the first element

array([1, 4, 7])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [62]:
arr[-1] # Access the last element of the array.

9

In [63]:
arr[-3:] # Access the last three elements of the array.

array([7, 8, 9])

Para el caso de las matrices, sucede algo similar.
Para acceder a los valores entre filas.

In [64]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
matriz[1:] # Access the second to the last row of the matrix. [row, column]

array([[4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores entre filas y columnas.



In [66]:
matriz[1:,0:2] # Access the second to the last row of the matrix and the first to the third column-1. [row: column, column: column]

array([[4, 5],
       [7, 8]])