In [2]:
%run -i 04_dimensiones.ipynb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[[[[[[[[[1 2 3]]]]]]]]]]
[[1 2 3]]
[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

Este método de NumPy nos permite generar arrays sin definir previamente una lista.

In [14]:
np.arange(0,10) # arange is a function that creates an array with a range of numbers, in this case from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Un tercer argumento permite definir un tamaño de paso.



In [15]:
np.arange(0,20,2) # arange can also take a step parameter, in this case 2 by 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

np.zeros() Nos permite definir estructuras o esquemas.



In [16]:
np.zeros(3) # zeros is a function that creates an array with a certain number of zeros, in this case 3

np.zeros((10,5)) # zeros can also take a tuple as a parameter, in this case a 10x5 matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

De igual manera, tenemos np.ones()



In [17]:
np.ones((4,4)) # ones is a function that creates an array with a certain number of ones, in this case a 4x4 matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.linspace() Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

In [18]:
np.linspace(0,10,10) # linspace is a function that creates an array with a range of numbers, in this case from 0 to 10 with 10 elements


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

También podemos crear una matriz con una diagonal de 1 y el resto de 9.



In [19]:
np.eye(10) # eye is a function that creates an identity matrix with a certain number of rows, in this case 10 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Otro método importante es generar números aleatorios.



In [20]:
np.random.rand() # random.rand is a function that creates a random number between 0 and 1

0.16706169584289587

También se pueden generar vectores.



In [21]:
np.random.rand(6) # random.rand can also take a parameter to create an array with a certain number of random numbers


array([0.71685718, 0.65650924, 0.58666552, 0.13750164, 0.65683035,
       0.22637144])

Y a su vez generar matrices.



In [22]:
np.random.randn(4,5) # also we can create an array with random numbers from a normal distribution in this case a 4x5 matrix

array([[ 1.32207549, -1.83760019,  1.53128717,  1.07047263,  1.11501101],
       [ 0.54303624,  0.31371349,  0.91394406, -1.23609621, -0.61005844],
       [ 0.3199624 ,  0.12347478, -1.11354249, -0.52538365, -0.20997242],
       [ 1.96975219, -0.19910434,  1.84284429, -0.96075313, -1.12013809]])

NumPy nos permite también generar números enteros.
En este caso números enteros entre el 1 y 14

In [23]:
np.random.randint(1,15) # random.randint is a function that creates a random integer between two numbers, in this case between 1 and 15

2

También podemos llevarlos a una estructura definida.



In [24]:
np.random.randint(1,15,(3,3)) # also we can create an array with random integers from a uniform distribution in this case a 3x3 matrix with numbers between 1 and 15

array([[ 5,  5,  1],
       [11,  3, 13],
       [ 1, 11,  6]])