In [4]:
%run -i 05_creando_array.ipynb

Hay 2 funciones muy importantes de los arreglos (Shape y Reshape). La forma de un arreglo nos va a decir con que estructura se está trabajando (tamaño, manipular, ingresar).

## Shape
Indica la forma del arreglo.

In [5]:
arr=np.random.randint(1,10,(3,2)) #crea un array de 3x2 con valores aleatorios entre 1 y 10
arr.shape

(3, 2)

In [6]:
arr

array([[3, 2],
       [5, 1],
       [5, 1]])

### Reshape
transforma el arreglo mientras se mantengan los elementos.

In [7]:
arr.reshape(1,6) #change the shape of the array to 1x6

array([[3, 2, 5, 1, 5, 1]])

In [8]:
arr.reshape(2,3) #change the shape of the array to 2x3

array([[3, 2, 5],
       [1, 5, 1]])

In [14]:
np.reshape(arr,(1,6)) #change the shape of the array to 1x6 other way

array([[3, 2, 5, 1, 5, 1]])

Se puede hacer un reshape como lo haría C.



In [15]:
np.reshape(arr,(2,3),"C") #change the shape of the array to 2x3 like C language

array([[3, 2, 5],
       [1, 5, 1]])

También se puede hacer reshape a como lo haría Fortran.



In [16]:
np.reshape(arr,(2,3),"F") #change the shape of the array to 2x3 like Fortran language

array([[3, 5, 1],
       [5, 2, 1]])

Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.



In [17]:
np.reshape(arr,(2,3),"A") #change the shape of the array to 2x3 like Fortran language

array([[3, 2, 5],
       [1, 5, 1]])

No puedes cambiar la "forma" a la "forma" original del array, si tienes un (3,3) no lo puedes pasar a (4,2). 
No respeta los 9 elementos del array original
