In [77]:
%run -i 06_shape_reshape.ipynb

Vamos a ver cuáles son las funciones que se utilizan normalmente con NumPy cuando analizamos los datos.



In [78]:
arr=np.random.randint(0,20,10) #10 numbers between 0 and 20
print(arr)

matriz=arr.reshape(2,5) #2 rows and 5 columns
matriz

[17 13  6  2  3  0  2 17  9 11]


array([[17, 13,  6,  2,  3],
       [ 0,  2, 17,  9, 11]])

.max Para el máximo



Podemos regresar los máximos de cada fila o columna especificando el eje

**Recuerda que:**

|    0 | Columnas |
| --- | -------- |
| 1 | Filas    |

In [79]:
print(matriz.max(1)) #max of each row in this case 1=rows 0=columns
print(matriz.max(0))

[17 17]
[17 13 17  9 11]


También tenemos .argmax() que nos devuelve la posición del elemento

In [80]:
arr

array([17, 13,  6,  2,  3,  0,  2, 17,  9, 11])

In [81]:
arr.argmax() #alsoe argmax it gives the index of the max value

0

En el caso de la matriz nos muestra con un 1 dónde se encuentra el mayor entre las columnas



In [82]:
print(matriz)
matriz.argmax(0) #index of the max value in each column

[[17 13  6  2  3]
 [ 0  2 17  9 11]]


array([0, 0, 1, 1, 1])

mDe forma análoga tenemos .min()



In [83]:
print(arr)
lol=arr.min() #min value
print(lol)


ruca=arr.argmin() # index of the min value
print(ruca)



[17 13  6  2  3  0  2 17  9 11]
0
5


In [84]:
matriz.min(0) #min value of each column


print(matriz.argmin(1))

[3 0]


Podemos saber la distancia entre el valor más bajo con el más alto.



In [85]:
arr

array([17, 13,  6,  2,  3,  0,  2, 17,  9, 11])

In [86]:
arr.ptp() #ptp is the difference between the max and the min value

# print(matriz)
# matriz.ptp(0)

17

In [87]:
matriz

array([[17, 13,  6,  2,  3],
       [ 0,  2, 17,  9, 11]])

In [88]:
matriz.ptp(0) #ptp is the difference between the max and the min value

array([17, 11, 11,  7,  8])

**Análisis estadístico**


Ordenar los elementos:

In [89]:
arr.sort() #sort the array
print(arr)

[ 0  2  2  3  6  9 11 13 17 17]


**Obtener un percentil:**

In [90]:
np.percentile(arr,50) #percentile 50

7.5

**Mediana:**

In [91]:
np.median(arr) #median

7.5

**Desviación estándar:**



In [92]:
np.std(arr)     #standard deviation

6.016643582596529

**Varianza:**



In [93]:
np.var(arr)    #variance

36.2

**Promedip**

In [94]:
np.mean(arr) #mean

8.0

Lo mismo aplica para las matrices.



In [95]:
print(matriz)
np.median(matriz,1) #median of each row

[[ 0  2  2  3  6]
 [ 9 11 13 17 17]]


array([ 2., 13.])

**Concatenación**


Se pueden unir dos arrays




In [96]:
a=np.array([[1,2],[3,4]])

b=np.array([5,6])

In [97]:
#np.concatenate((a,b),axis=0) #concatenate the arrays it has to be the same shape

El error anterior es debido a que ‘a’ tiene 2 dimensiones, mientras que ‘b’ tiene 1.



In [98]:
a.ndim #number of dimensions
#b.ndim

2

In [99]:
b.ndim

1

Debemos poner ‘b’ en 2 dimensiones también.



In [100]:
b=np.expand_dims(b,axis=0) #expand the dimensions of the array to be able to concatenate axis=0 is the row axis=1 is the column
#np.concatenate((a,b),axis=0)
b

array([[5, 6]])

In [101]:
np.concatenate((a,b),axis=0) #concatenate the arrays it has to be the same shape

array([[1, 2],
       [3, 4],
       [5, 6]])

De igual manera, podemos agregarlo en el otro eje



In [103]:
#np.concatenate((a,b),axis=1) #concatenate the arrays it has to be the same shape but in this case axis=1 is the column

Como ‘b’ es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

La transpuesta pone nuestro array en sentido opuesto, si el array original es (1,2), con la transpuesta quedará (2,1)

In [104]:
b.T #transpose the array

array([[5],
       [6]])

In [105]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])